# load the data from the dataset to check the data quality

In [1]:
import pandas as pd
import numpy as np

# Loading the dataset in notebook

In [2]:
accounts = pd.read_csv(
    r"D:\Customer_churn_risk_analysis\data_raw\ravenstack_accounts.csv"
)
accounts.head(5)

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag
0,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False
1,A-43a9e3,Company_1,FinTech,IN,2023-08-17,other,Basic,18,False,True
2,A-0a282f,Company_2,DevTools,US,2024-08-27,organic,Basic,1,False,False
3,A-1f0ac7,Company_3,HealthTech,UK,2023-08-27,other,Basic,24,True,False
4,A-ce550d,Company_4,HealthTech,US,2024-10-27,event,Enterprise,35,False,True

# check the quality check of the dataset

In [3]:
accounts.columns

Index(['account_id', 'account_name', 'industry', 'country', 'signup_date',
       'referral_source', 'plan_tier', 'seats', 'is_trial', 'churn_flag'],
      dtype='str')

# check the infomation, describe, and checking the duplicate and null values

In [4]:
accounts.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   account_id       500 non-null    str
 1   account_name     500 non-null    str
 2   industry         500 non-null    str
 3   country          500 non-null    str
 4   signup_date      500 non-null    str
 5   referral_source  500 non-null    str
 6   plan_tier        500 non-null    str
 7   seats            500 non-null    int64
 8   is_trial         500 non-null    bool
 9   churn_flag       500 non-null    bool
dtypes: bool(2), int64(1), str(7)
memory usage: 32.4 KB

In [5]:
accounts.describe()

            seats
count  500.000000
mean    20.560000
std     21.044718
min      1.000000
25%      5.000000
50%     15.000000
75%     28.000000
max    163.000000

In [6]:
accounts.isnull()

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False,False,False

In [7]:
accounts.isnull().sum()

account_id         0
account_name       0
industry           0
country            0
signup_date        0
referral_source    0
plan_tier          0
seats              0
is_trial           0
churn_flag         0
dtype: int64

# load churn_Event csv files

In [8]:
churn_events = pd.read_csv(
    r"D:\Customer_churn_risk_analysis\data_raw\ravenstack_churn_events.csv"
)

# head and tail

In [9]:
churn_events.head(5)

,churn_event_id,account_id,churn_date,reason_code,refund_amount_usd,preceding_upgrade_flag,preceding_downgrade_flag,is_reactivation,feedback_text
0,C-816288,A-c37cab,2024-10-27,pricing,4.03,False,False,False,switched to competitor
1,C-5a81e7,A-37f969,2024-06-25,support,96.45,True,False,False,NaN
2,C-a174be,A-b07346,2024-11-12,budget,0.00,False,False,False,missing features
3,C-accb39,A-1e50e0,2023-11-01,budget,54.94,False,False,False,switched to competitor
4,C-92f889,A-956988,2024-12-30,unknown,0.00,False,True,True,too expensive

In [10]:
churn_events.tail(5)

,churn_event_id,account_id,churn_date,reason_code,refund_amount_usd,preceding_upgrade_flag,preceding_downgrade_flag,is_reactivation,feedback_text
595,C-b56a35,A-702032,2024-06-14,competitor,0.00,False,False,False,switched to competitor
596,C-7e7822,A-dbc825,2024-02-03,budget,0.00,False,False,False,NaN
597,C-484fba,A-0a282f,2024-12-31,support,62.66,False,True,False,too expensive
598,C-22f536,A-e5d6ab,2024-05-11,competitor,0.00,True,False,False,NaN
599,C-5e0b68,A-1f559b,2024-09-28,features,0.00,False,False,False,NaN

In [11]:
churn_events.isnull().sum()

churn_event_id                0
account_id                    0
churn_date                    0
reason_code                   0
refund_amount_usd             0
preceding_upgrade_flag        0
preceding_downgrade_flag      0
is_reactivation               0
feedback_text               148
dtype: int64

# First calculate the percentage:

In [12]:
churn_events['feedback_text'].isna().mean() * 100

np.float64(24.666666666666668)

In [13]:
round(churn_events['feedback_text'].isna().mean() * 100, 2)

np.float64(24.67)

In [14]:
churn_events.shape

(600, 9)

In [15]:
churn_events_cleaned = churn_events.copy()

churn_events_cleaned['feedback_text'] = (
    churn_events_cleaned['feedback_text']
    .fillna('No feedback provided')
)

In [16]:
churn_events_cleaned.isnull().sum()

churn_event_id              0
account_id                  0
churn_date                  0
reason_code                 0
refund_amount_usd           0
preceding_upgrade_flag      0
preceding_downgrade_flag    0
is_reactivation             0
feedback_text               0
dtype: int64

In [17]:
churn_events_cleaned.head()

,churn_event_id,account_id,churn_date,reason_code,refund_amount_usd,preceding_upgrade_flag,preceding_downgrade_flag,is_reactivation,feedback_text
0,C-816288,A-c37cab,2024-10-27,pricing,4.03,False,False,False,switched to competitor
1,C-5a81e7,A-37f969,2024-06-25,support,96.45,True,False,False,No feedback provided
2,C-a174be,A-b07346,2024-11-12,budget,0.00,False,False,False,missing features
3,C-accb39,A-1e50e0,2023-11-01,budget,54.94,False,False,False,switched to competitor
4,C-92f889,A-956988,2024-12-30,unknown,0.00,False,True,True,too expensive

In [18]:
churn_events_cleaned.to_csv(
    "../data_cleaned/ravenstack_churn_events_cleaned.csv",
    index=False
)

# importing feature_usage

In [19]:
feature_usage = pd.read_csv(r"D:\Customer_churn_risk_analysis\data_raw\ravenstack_feature_usage.csv")
feature_usage.head(5)

,usage_id,subscription_id,usage_date,feature_name,usage_count,usage_duration_secs,error_count,is_beta_feature
0,U-1c6c24,S-0fcf7d,2023-07-27,feature_20,9,5004,0,False
1,U-f07cb8,S-c25263,2023-08-07,feature_5,9,369,0,False
2,U-096807,S-f29e7f,2023-12-07,feature_3,9,1458,0,False
3,U-6b1580,S-be655e,2024-07-28,feature_40,5,2085,0,False
4,U-720a29,S-f9b1d0,2024-12-02,feature_12,12,900,0,False

In [20]:
feature_usage.describe()

        usage_count  usage_duration_secs   error_count
count  25000.000000         25000.000000  25000.000000
mean      10.021000          3042.202880      0.564280
std        3.143729          2056.544615      1.012595
min        0.000000             0.000000      0.000000
25%        8.000000          1350.000000      0.000000
50%       10.000000          2760.000000      0.000000
75%       12.000000          4400.000000      1.000000
max       26.000000         12696.000000      8.000000

In [21]:
feature_usage.isnull().sum()

usage_id               0
subscription_id        0
usage_date             0
feature_name           0
usage_count            0
usage_duration_secs    0
error_count            0
is_beta_feature        0
dtype: int64

In [22]:
churn_events_cleaned.to_csv(
    r"D:\Customer_churn_risk_analysis\data_raw\ravenstack_feature_usage_cleaned.csv",
    index=False
)

# importing subscription

In [23]:
subscriptions = pd.read_csv(r"D:\Customer_churn_risk_analysis\data_raw\ravenstack_subscriptions.csv")
subscriptions.head(5)

,subscription_id,account_id,start_date,end_date,plan_tier,seats,mrr_amount,arr_amount,is_trial,upgrade_flag,downgrade_flag,churn_flag,billing_frequency,auto_renew_flag
0,S-8cec59,A-3c1a3f,2023-12-23,2024-04-12,Enterprise,14,2786,33432,False,False,False,True,monthly,True
1,S-0f6f44,A-9b9fe9,2024-06-11,NaN,Pro,17,833,9996,False,False,False,False,monthly,True
2,S-51c0d1,A-659280,2024-11-25,NaN,Enterprise,62,0,0,True,True,False,False,annual,False
3,S-f81687,A-e7a1e2,2024-11-23,2024-12-13,Enterprise,5,995,11940,False,False,False,True,monthly,True
4,S-cff5a2,A-ba6516,2024-01-10,NaN,Enterprise,27,5373,64476,False,False,False,False,monthly,True

In [24]:
subscriptions.describe()

             seats    mrr_amount     arr_amount
count  5000.000000   5000.000000    5000.000000
mean     29.852000   2267.749400   27212.992800
std      23.089771   3421.375348   41056.504178
min       1.000000      0.000000       0.000000
25%      14.000000    285.000000    3420.000000
50%      24.000000    931.000000   11172.000000
75%      40.000000   2786.000000   33432.000000
max     189.000000  33830.000000  405960.000000

In [25]:
subscriptions.isnull().sum()

subscription_id         0
account_id              0
start_date              0
end_date             4514
plan_tier               0
seats                   0
mrr_amount              0
arr_amount              0
is_trial                0
upgrade_flag            0
downgrade_flag          0
churn_flag              0
billing_frequency       0
auto_renew_flag         0
dtype: int64

In [26]:
subscriptions[subscriptions['end_date'].isna()]['churn_flag'].value_counts()

churn_flag
False    4514
Name: count, dtype: int64

In [27]:
subscriptions[subscriptions['end_date'].isna()]['plan_tier'].value_counts()

plan_tier
Enterprise    1551
Pro           1513
Basic         1450
Name: count, dtype: int64

In [28]:
subscriptions[
    subscriptions['end_date'].isna()
]['auto_renew_flag'].value_counts()

auto_renew_flag
True     3615
False     899
Name: count, dtype: int64

In [29]:
round(subscriptions['end_date'].isna().mean()*100,2)

np.float64(90.28)

In [30]:
subscriptions_cleaned =subscriptions.copy()

In [31]:
subscriptions_cleaned['start_date'] = pd.to_datetime(subscriptions_cleaned['start_date'])
subscriptions_cleaned['end_date'] = pd.to_datetime(subscriptions_cleaned['end_date'])

In [32]:
subscriptions_cleaned.head(5)

,subscription_id,account_id,start_date,end_date,plan_tier,seats,mrr_amount,arr_amount,is_trial,upgrade_flag,downgrade_flag,churn_flag,billing_frequency,auto_renew_flag
0,S-8cec59,A-3c1a3f,2023-12-23,2024-04-12,Enterprise,14,2786,33432,False,False,False,True,monthly,True
1,S-0f6f44,A-9b9fe9,2024-06-11,NaT,Pro,17,833,9996,False,False,False,False,monthly,True
2,S-51c0d1,A-659280,2024-11-25,NaT,Enterprise,62,0,0,True,True,False,False,annual,False
3,S-f81687,A-e7a1e2,2024-11-23,2024-12-13,Enterprise,5,995,11940,False,False,False,True,monthly,True
4,S-cff5a2,A-ba6516,2024-01-10,NaT,Enterprise,27,5373,64476,False,False,False,False,monthly,True

In [33]:
subscriptions_cleaned.isnull().sum()

subscription_id         0
account_id              0
start_date              0
end_date             4514
plan_tier               0
seats                   0
mrr_amount              0
arr_amount              0
is_trial                0
upgrade_flag            0
downgrade_flag          0
churn_flag              0
billing_frequency       0
auto_renew_flag         0
dtype: int64

In [34]:
subscriptions_cleaned.to_csv(
    r"D:\Customer_churn_risk_analysis\data_raw\ravenstack_subscriptions.csv",
    index=False
)

# suppport ticket

In [35]:
support_ticket = pd.read_csv(r"D:\Customer_churn_risk_analysis\data_raw\ravenstack_support_tickets.csv")
support_ticket.head(5)

,ticket_id,account_id,submitted_at,closed_at,resolution_time_hours,priority,first_response_time_minutes,satisfaction_score,escalation_flag
0,T-0024de,A-712f1c,2023-07-27,2023-07-28 03:00:00,27.0,high,74,NaN,False
1,T-4d04b9,A-e43bf7,2024-07-08,2024-07-09 03:00:00,27.0,urgent,144,NaN,False
2,T-d5e12f,A-0f3e88,2024-10-17,2024-10-17 19:00:00,19.0,urgent,93,4.0,False
3,T-dfce9a,A-4c56c9,2024-09-08,2024-09-09 23:00:00,47.0,medium,126,5.0,False
4,T-c59f77,A-6f8ad2,2024-11-30,2024-12-01 02:00:00,26.0,medium,8,NaN,False

In [36]:
support_ticket.isnull().sum()

ticket_id                        0
account_id                       0
submitted_at                     0
closed_at                        0
resolution_time_hours            0
priority                         0
first_response_time_minutes      0
satisfaction_score             825
escalation_flag                  0
dtype: int64

In [37]:
support_cleaned =support_ticket.copy()

In [38]:
support_cleaned['satisfaction_score'].mean()

np.float64(3.981276595744681)

In [39]:
support_cleaned['satisfaction_score'].isna().sum()

np.int64(825)

# text label

In [40]:
support_cleaned['satisfaction_status'] =support_cleaned['satisfaction_score'].apply(
    lambda x: 'not provide' if pd.isna(x) else 'Provide'
)

In [41]:
support_cleaned.to_csv(
    "../data_cleaned/ravenstack_support_tickets_cleaned.csv",
    index=False
)

In [42]:
accounts.head(5)

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag
0,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False
1,A-43a9e3,Company_1,FinTech,IN,2023-08-17,other,Basic,18,False,True
2,A-0a282f,Company_2,DevTools,US,2024-08-27,organic,Basic,1,False,False
3,A-1f0ac7,Company_3,HealthTech,UK,2023-08-27,other,Basic,24,True,False
4,A-ce550d,Company_4,HealthTech,US,2024-10-27,event,Enterprise,35,False,True